### PR TITLE
Add filter_files_log.bro Plugin

### PR DESCRIPTION
**Pull request by aeppert**

### CODE REVIEW

**Comment by hosom** [comment]
@aeppert I know it's been a while since you posted this. I'm working on moving this module to be a package over the next couple days. think its still worthwhile to include this functionality?

**Comment by aeppert** [comment]
@hosom I would suggest it to remain, yes. One of the major things people want is a means of culling the files.log.

**Comment by hosom** [comment]
I'll go ahead and get this into the code then. Look for a push sometime this week.

**Comment by hosom** [comment]
@aeppert I've given this one a lot of thought and I think this would be better suited in another package... so I made one for it. Give a look at https://github.com/hosom/log-filters and tell me what you think

**Comment by aeppert** [comment]
This is a great idea and makes the most sense over all.

**Pull request closed without merging**
